name: Build and Deploy Code
# on: [push, pull_request]
on: 
  push:
    branches:
      - "master"
    pull_request:
      - "master"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi ti vic
        run: echo "hello vic"